site_name: My Blog
theme:
    name: material
    language: en
    features:
        - navigation.tracking # Adds "last visited" tracking
        - navigation.top # Places navigation at the top
    palette:
        scheme: slate
        primary: indigo
        accent: light blue
    favicon: images/favicon.ico

markdown_extensions:
    - toc:
          permalink: True
    - admonition
    - pymdownx.superfences
    - pymdownx.highlight

plugins:
    - search
    - ultralytics:
          verbose: true
          enabled: true
          add_desc: true
          add_image: true
          add_keywords: true
          add_share_buttons: true
          add_authors: true
          add_json_ld: true
          add_css: true

site_url: https://theonesud.com
